/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/typed/servicebinding/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeServiceV1alpha2 struct {
	*testing.Fake
}

func (c *FakeServiceV1alpha2) ServiceBindings(namespace string) v1alpha2.ServiceBindingInterface {
	return &FakeServiceBindings{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeServiceV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
