# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  name: custom
  annotations:
    # disable the default binding projection
    projection.service.binding/type: Custom
spec:
  # pointing application at a real resource, but not one we can reconcile as 
  # PodSpecable, replace with the desired application.
  application:
    apiVersion: v1
    kind: ConfigMap
    name: custom
  # direct Secret reference is used for compatibility, but not recommended for dynamically provisioned services
  service:
    apiVersion: v1
    kind: Secret
    name: custom
