/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/vmware-labs/service-bindings/pkg/apis/servicebindinginternal/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceBindingProjections implements ServiceBindingProjectionInterface
type FakeServiceBindingProjections struct {
	Fake *FakeInternalV1alpha2
	ns   string
}

var servicebindingprojectionsResource = schema.GroupVersionResource{Group: "internal.service.binding", Version: "v1alpha2", Resource: "servicebindingprojections"}

var servicebindingprojectionsKind = schema.GroupVersionKind{Group: "internal.service.binding", Version: "v1alpha2", Kind: "ServiceBindingProjection"}

// Get takes name of the serviceBindingProjection, and returns the corresponding serviceBindingProjection object, and an error if there is any.
func (c *FakeServiceBindingProjections) Get(name string, options v1.GetOptions) (result *v1alpha2.ServiceBindingProjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicebindingprojectionsResource, c.ns, name), &v1alpha2.ServiceBindingProjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ServiceBindingProjection), err
}

// List takes label and field selectors, and returns the list of ServiceBindingProjections that match those selectors.
func (c *FakeServiceBindingProjections) List(opts v1.ListOptions) (result *v1alpha2.ServiceBindingProjectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicebindingprojectionsResource, servicebindingprojectionsKind, c.ns, opts), &v1alpha2.ServiceBindingProjectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.ServiceBindingProjectionList{ListMeta: obj.(*v1alpha2.ServiceBindingProjectionList).ListMeta}
	for _, item := range obj.(*v1alpha2.ServiceBindingProjectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceBindingProjections.
func (c *FakeServiceBindingProjections) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicebindingprojectionsResource, c.ns, opts))

}

// Create takes the representation of a serviceBindingProjection and creates it.  Returns the server's representation of the serviceBindingProjection, and an error, if there is any.
func (c *FakeServiceBindingProjections) Create(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (result *v1alpha2.ServiceBindingProjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicebindingprojectionsResource, c.ns, serviceBindingProjection), &v1alpha2.ServiceBindingProjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ServiceBindingProjection), err
}

// Update takes the representation of a serviceBindingProjection and updates it. Returns the server's representation of the serviceBindingProjection, and an error, if there is any.
func (c *FakeServiceBindingProjections) Update(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (result *v1alpha2.ServiceBindingProjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicebindingprojectionsResource, c.ns, serviceBindingProjection), &v1alpha2.ServiceBindingProjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ServiceBindingProjection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceBindingProjections) UpdateStatus(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (*v1alpha2.ServiceBindingProjection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicebindingprojectionsResource, "status", c.ns, serviceBindingProjection), &v1alpha2.ServiceBindingProjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ServiceBindingProjection), err
}

// Delete takes name of the serviceBindingProjection and deletes it. Returns an error if one occurs.
func (c *FakeServiceBindingProjections) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicebindingprojectionsResource, c.ns, name), &v1alpha2.ServiceBindingProjection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceBindingProjections) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicebindingprojectionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.ServiceBindingProjectionList{})
	return err
}

// Patch applies the patch and returns the patched serviceBindingProjection.
func (c *FakeServiceBindingProjections) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ServiceBindingProjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicebindingprojectionsResource, c.ns, name, pt, data, subresources...), &v1alpha2.ServiceBindingProjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ServiceBindingProjection), err
}
