# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  name: mappings
spec:
  application:
    apiVersion: batch/v1
    kind: Job
    name: mappings
  # direct Secret reference is used for compatibility, but not recommended for dynamically provisioned services
  service:
    apiVersion: v1
    kind: Secret
    name: mappings
  mappings:
  - name: uri
    value: "https://{{ urlquery .username }}:{{ urlquery .password }}@{{ .host }}"
  env:
  - name: GAME_SERVER
    key: uri
