# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  name: controlled-resource
spec:
  # direct Secret reference is used for compatibility, but not recommended for dynamically provisioned services
  service:
    apiVersion: v1
    kind: Secret
    name: controlled-resource
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    # use a label selector since we may not know the name of the controlled resource
    selector:
      matchLabels:
        serving.knative.dev/service: controlled-resource
  env:
  - name: TARGET
    key: target
