# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: controlled-resource
spec:
  template:
    spec:
      containers:
        # from https://knative.dev/docs/serving/samples/hello-world/helloworld-go/
        - image: gcr.io/knative-samples/helloworld-go
