/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-labs/service-bindings/pkg/apis/labs/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvisionedServices implements ProvisionedServiceInterface
type FakeProvisionedServices struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var provisionedservicesResource = schema.GroupVersionResource{Group: "bindings.labs.vmware.com", Version: "v1alpha1", Resource: "provisionedservices"}

var provisionedservicesKind = schema.GroupVersionKind{Group: "bindings.labs.vmware.com", Version: "v1alpha1", Kind: "ProvisionedService"}

// Get takes name of the provisionedService, and returns the corresponding provisionedService object, and an error if there is any.
func (c *FakeProvisionedServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(provisionedservicesResource, c.ns, name), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// List takes label and field selectors, and returns the list of ProvisionedServices that match those selectors.
func (c *FakeProvisionedServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProvisionedServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(provisionedservicesResource, provisionedservicesKind, c.ns, opts), &v1alpha1.ProvisionedServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProvisionedServiceList{ListMeta: obj.(*v1alpha1.ProvisionedServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProvisionedServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested provisionedServices.
func (c *FakeProvisionedServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(provisionedservicesResource, c.ns, opts))

}

// Create takes the representation of a provisionedService and creates it.  Returns the server's representation of the provisionedService, and an error, if there is any.
func (c *FakeProvisionedServices) Create(ctx context.Context, provisionedService *v1alpha1.ProvisionedService, opts v1.CreateOptions) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(provisionedservicesResource, c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// Update takes the representation of a provisionedService and updates it. Returns the server's representation of the provisionedService, and an error, if there is any.
func (c *FakeProvisionedServices) Update(ctx context.Context, provisionedService *v1alpha1.ProvisionedService, opts v1.UpdateOptions) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(provisionedservicesResource, c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvisionedServices) UpdateStatus(ctx context.Context, provisionedService *v1alpha1.ProvisionedService, opts v1.UpdateOptions) (*v1alpha1.ProvisionedService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(provisionedservicesResource, "status", c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// Delete takes name of the provisionedService and deletes it. Returns an error if one occurs.
func (c *FakeProvisionedServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(provisionedservicesResource, c.ns, name), &v1alpha1.ProvisionedService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvisionedServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(provisionedservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProvisionedServiceList{})
	return err
}

// Patch applies the patch and returns the patched provisionedService.
func (c *FakeProvisionedServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(provisionedservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}
