# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: application
          # built with paketo builder from https://github.com/spring-projects/spring-petclinic
          image: scothis/petclinic:service-bindings
          env:
          # tell the application to use mysql instead of the default embedded database
          - name: SPRING_PROFILES_ACTIVE
            value: mysql
          ports:
          - name: http
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 20
            periodSeconds: 5
