/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"time"

	v1alpha2 "github.com/vmware-labs/service-bindings/pkg/apis/serviceinternal/v1alpha2"
	scheme "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceBindingProjectionsGetter has a method to return a ServiceBindingProjectionInterface.
// A group's client should implement this interface.
type ServiceBindingProjectionsGetter interface {
	ServiceBindingProjections(namespace string) ServiceBindingProjectionInterface
}

// ServiceBindingProjectionInterface has methods to work with ServiceBindingProjection resources.
type ServiceBindingProjectionInterface interface {
	Create(*v1alpha2.ServiceBindingProjection) (*v1alpha2.ServiceBindingProjection, error)
	Update(*v1alpha2.ServiceBindingProjection) (*v1alpha2.ServiceBindingProjection, error)
	UpdateStatus(*v1alpha2.ServiceBindingProjection) (*v1alpha2.ServiceBindingProjection, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.ServiceBindingProjection, error)
	List(opts v1.ListOptions) (*v1alpha2.ServiceBindingProjectionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ServiceBindingProjection, err error)
	ServiceBindingProjectionExpansion
}

// serviceBindingProjections implements ServiceBindingProjectionInterface
type serviceBindingProjections struct {
	client rest.Interface
	ns     string
}

// newServiceBindingProjections returns a ServiceBindingProjections
func newServiceBindingProjections(c *InternalV1alpha2Client, namespace string) *serviceBindingProjections {
	return &serviceBindingProjections{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceBindingProjection, and returns the corresponding serviceBindingProjection object, and an error if there is any.
func (c *serviceBindingProjections) Get(name string, options v1.GetOptions) (result *v1alpha2.ServiceBindingProjection, err error) {
	result = &v1alpha2.ServiceBindingProjection{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceBindingProjections that match those selectors.
func (c *serviceBindingProjections) List(opts v1.ListOptions) (result *v1alpha2.ServiceBindingProjectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.ServiceBindingProjectionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceBindingProjections.
func (c *serviceBindingProjections) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceBindingProjection and creates it.  Returns the server's representation of the serviceBindingProjection, and an error, if there is any.
func (c *serviceBindingProjections) Create(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (result *v1alpha2.ServiceBindingProjection, err error) {
	result = &v1alpha2.ServiceBindingProjection{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		Body(serviceBindingProjection).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceBindingProjection and updates it. Returns the server's representation of the serviceBindingProjection, and an error, if there is any.
func (c *serviceBindingProjections) Update(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (result *v1alpha2.ServiceBindingProjection, err error) {
	result = &v1alpha2.ServiceBindingProjection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		Name(serviceBindingProjection.Name).
		Body(serviceBindingProjection).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *serviceBindingProjections) UpdateStatus(serviceBindingProjection *v1alpha2.ServiceBindingProjection) (result *v1alpha2.ServiceBindingProjection, err error) {
	result = &v1alpha2.ServiceBindingProjection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		Name(serviceBindingProjection.Name).
		SubResource("status").
		Body(serviceBindingProjection).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceBindingProjection and deletes it. Returns an error if one occurs.
func (c *serviceBindingProjections) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceBindingProjections) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebindingprojections").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceBindingProjection.
func (c *serviceBindingProjections) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ServiceBindingProjection, err error) {
	result = &v1alpha2.ServiceBindingProjection{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicebindingprojections").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
