/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"time"

	v1alpha2 "github.com/vmware-labs/service-bindings/pkg/apis/service/v1alpha2"
	scheme "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceBindingsGetter has a method to return a ServiceBindingInterface.
// A group's client should implement this interface.
type ServiceBindingsGetter interface {
	ServiceBindings(namespace string) ServiceBindingInterface
}

// ServiceBindingInterface has methods to work with ServiceBinding resources.
type ServiceBindingInterface interface {
	Create(*v1alpha2.ServiceBinding) (*v1alpha2.ServiceBinding, error)
	Update(*v1alpha2.ServiceBinding) (*v1alpha2.ServiceBinding, error)
	UpdateStatus(*v1alpha2.ServiceBinding) (*v1alpha2.ServiceBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.ServiceBinding, error)
	List(opts v1.ListOptions) (*v1alpha2.ServiceBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ServiceBinding, err error)
	ServiceBindingExpansion
}

// serviceBindings implements ServiceBindingInterface
type serviceBindings struct {
	client rest.Interface
	ns     string
}

// newServiceBindings returns a ServiceBindings
func newServiceBindings(c *ServiceV1alpha2Client, namespace string) *serviceBindings {
	return &serviceBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceBinding, and returns the corresponding serviceBinding object, and an error if there is any.
func (c *serviceBindings) Get(name string, options v1.GetOptions) (result *v1alpha2.ServiceBinding, err error) {
	result = &v1alpha2.ServiceBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceBindings that match those selectors.
func (c *serviceBindings) List(opts v1.ListOptions) (result *v1alpha2.ServiceBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.ServiceBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceBindings.
func (c *serviceBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceBinding and creates it.  Returns the server's representation of the serviceBinding, and an error, if there is any.
func (c *serviceBindings) Create(serviceBinding *v1alpha2.ServiceBinding) (result *v1alpha2.ServiceBinding, err error) {
	result = &v1alpha2.ServiceBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicebindings").
		Body(serviceBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceBinding and updates it. Returns the server's representation of the serviceBinding, and an error, if there is any.
func (c *serviceBindings) Update(serviceBinding *v1alpha2.ServiceBinding) (result *v1alpha2.ServiceBinding, err error) {
	result = &v1alpha2.ServiceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebindings").
		Name(serviceBinding.Name).
		Body(serviceBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *serviceBindings) UpdateStatus(serviceBinding *v1alpha2.ServiceBinding) (result *v1alpha2.ServiceBinding, err error) {
	result = &v1alpha2.ServiceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebindings").
		Name(serviceBinding.Name).
		SubResource("status").
		Body(serviceBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceBinding and deletes it. Returns an error if one occurs.
func (c *serviceBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceBinding.
func (c *serviceBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ServiceBinding, err error) {
	result = &v1alpha2.ServiceBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
