# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: overridden-type-provider
type: Opaque
stringData:
  type: original-type
  provider: original-provider
