# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: overridden-type-provider
spec:
  template:
    spec:
      containers:
      - name: workload
        image: ubuntu:bionic
        command: ["env"]
      enableServiceLinks: false
      restartPolicy: OnFailure
