/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	imageable "github.com/vmware-labs/service-bindings/pkg/client/injection/ducks/duck/v1alpha1/imageable"
	injection "knative.dev/pkg/injection"
)

var Get = imageable.Get

func init() {
	injection.Fake.RegisterDuck(imageable.WithDuck)
}
