/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	v1alpha3 "github.com/vmware-tanzu/servicebinding/pkg/apis/servicebinding/v1alpha3"
	"github.com/vmware-tanzu/servicebinding/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ServicebindingV1alpha3Interface interface {
	RESTClient() rest.Interface
	ServiceBindingsGetter
}

// ServicebindingV1alpha3Client is used to interact with features provided by the servicebinding.io group.
type ServicebindingV1alpha3Client struct {
	restClient rest.Interface
}

func (c *ServicebindingV1alpha3Client) ServiceBindings(namespace string) ServiceBindingInterface {
	return newServiceBindings(c, namespace)
}

// NewForConfig creates a new ServicebindingV1alpha3Client for the given config.
func NewForConfig(c *rest.Config) (*ServicebindingV1alpha3Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ServicebindingV1alpha3Client{client}, nil
}

// NewForConfigOrDie creates a new ServicebindingV1alpha3Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ServicebindingV1alpha3Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ServicebindingV1alpha3Client for the given RESTClient.
func New(c rest.Interface) *ServicebindingV1alpha3Client {
	return &ServicebindingV1alpha3Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha3.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ServicebindingV1alpha3Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
