# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.bindings.labs.vmware.com
  labels:
    bindings.labs.vmware.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: service-bindings
  failurePolicy: Fail
  name: defaulting.webhook.bindings.labs.vmware.com
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.bindings.labs.vmware.com
  labels:
    bindings.labs.vmware.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: service-bindings
  failurePolicy: Fail
  name: validation.webhook.bindings.labs.vmware.com
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.bindings.labs.vmware.com
  labels:
    bindings.labs.vmware.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: service-bindings
  failurePolicy: Fail
  name: config.webhook.bindings.labs.vmware.com
  namespaceSelector:
    matchExpressions:
    - key: bindings.labs.vmware.com/release
      operator: Exists
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: servicebindingprojections.webhook.bindings.labs.vmware.com
  labels:
    bindings.labs.vmware.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: service-bindings
  failurePolicy: Fail
  name: servicebindingprojections.webhook.bindings.labs.vmware.com
  sideEffects: None
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: service-bindings
  labels:
    bindings.labs.vmware.com/release: devel
# data is populated at runtime.
