/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by injection-gen. DO NOT EDIT.

package provisionedservice

import (
	context "context"

	provisionedservice "github.com/vmware-labs/service-bindings/pkg/client/injection/informers/labs/v1alpha1/provisionedservice"
	v1alpha1provisionedservice "github.com/vmware-labs/service-bindings/pkg/client/injection/reconciler/labs/v1alpha1/provisionedservice"
	configmap "knative.dev/pkg/configmap"
	controller "knative.dev/pkg/controller"
	logging "knative.dev/pkg/logging"
)

// TODO: PLEASE COPY AND MODIFY THIS FILE AS A STARTING POINT

// NewController creates a Reconciler for ProvisionedService and returns the result of NewImpl.
func NewController(
	ctx context.Context,
	cmw configmap.Watcher,
) *controller.Impl {
	logger := logging.FromContext(ctx)

	provisionedserviceInformer := provisionedservice.Get(ctx)

	// TODO: setup additional informers here.

	r := &Reconciler{}
	impl := v1alpha1provisionedservice.NewImpl(ctx, r)

	logger.Info("Setting up event handlers.")

	provisionedserviceInformer.Informer().AddEventHandler(controller.HandleAll(impl.Enqueue))

	// TODO: add additional informer event handlers here.

	return impl
}
