/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	serviceable "github.com/vmware-labs/service-bindings/pkg/client/injection/ducks/duck/v1alpha1/serviceable"
	injection "knative.dev/pkg/injection"
)

var Get = serviceable.Get

func init() {
	injection.Fake.RegisterDuck(serviceable.WithDuck)
}
