/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ProvisionedServiceListerExpansion allows custom methods to be added to
// ProvisionedServiceLister.
type ProvisionedServiceListerExpansion interface{}

// ProvisionedServiceNamespaceListerExpansion allows custom methods to be added to
// ProvisionedServiceNamespaceLister.
type ProvisionedServiceNamespaceListerExpansion interface{}
