/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	provisionedservice "github.com/vmware-labs/service-bindings/pkg/client/injection/informers/bindings/v1alpha1/provisionedservice"
	fake "github.com/vmware-labs/service-bindings/pkg/client/injection/informers/factory/fake"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = provisionedservice.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Bindings().V1alpha1().ProvisionedServices()
	return context.WithValue(ctx, provisionedservice.Key{}, inf), inf.Informer()
}
