/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/servicebinding/pkg/apis/labs/v1alpha1"
	"github.com/vmware-tanzu/servicebinding/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type BindingsV1alpha1Interface interface {
	RESTClient() rest.Interface
	ProvisionedServicesGetter
}

// BindingsV1alpha1Client is used to interact with features provided by the bindings.labs.vmware.com group.
type BindingsV1alpha1Client struct {
	restClient rest.Interface
}

func (c *BindingsV1alpha1Client) ProvisionedServices(namespace string) ProvisionedServiceInterface {
	return newProvisionedServices(c, namespace)
}

// NewForConfig creates a new BindingsV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*BindingsV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &BindingsV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new BindingsV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *BindingsV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new BindingsV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *BindingsV1alpha1Client {
	return &BindingsV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *BindingsV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
