# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-petclinic-db
type: Opaque
stringData:
  type: mysql
  provider: mariadb
  host: spring-petclinic-db
  port: "3306"
  database: default
  # demo credentials
  username: user
  password: pass

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-db
spec:
  ports:
  - port: 3306
  selector:
    app: spring-petclinic-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-db
  labels:
    app: spring-petclinic-db
spec:
  selector:
    matchLabels:
      app: spring-petclinic-db
  template:
    metadata:
      labels:
        app: spring-petclinic-db
    spec:
      # no persistance configured, the database will be reset when the pod terminates
      containers:
      - image: mariadb:10.5
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: spring-petclinic-db
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-petclinic-db
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: spring-petclinic-db
              key: database
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          tcpSocket:
            port: mysql
        readinessProbe:
          tcpSocket:
            port: mysql
        startupProbe:
          tcpSocket:
            port: mysql
