# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: workload
          # built with paketo builder from https://github.com/spring-projects/spring-petclinic
          image: ghcr.io/vmware-tanzu/servicebinding/test/petclinic:20200922
          env:
          # tell the workload to use mysql instead of the default embedded database
          - name: SPRING_PROFILES_ACTIVE
            value: mysql
          ports:
          - name: http
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 20
            periodSeconds: 5
