/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

// ServiceBindingListerExpansion allows custom methods to be added to
// ServiceBindingLister.
type ServiceBindingListerExpansion interface{}

// ServiceBindingNamespaceListerExpansion allows custom methods to be added to
// ServiceBindingNamespaceLister.
type ServiceBindingNamespaceListerExpansion interface{}
