/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"

	bindingsv1alpha1 "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/typed/bindings/v1alpha1"
	duckv1alpha1 "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/typed/duck/v1alpha1"
	servicev1alpha2 "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/typed/service/v1alpha2"
	internalv1alpha2 "github.com/vmware-labs/service-bindings/pkg/client/clientset/versioned/typed/serviceinternal/v1alpha2"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	BindingsV1alpha1() bindingsv1alpha1.BindingsV1alpha1Interface
	DuckV1alpha1() duckv1alpha1.DuckV1alpha1Interface
	ServiceV1alpha2() servicev1alpha2.ServiceV1alpha2Interface
	InternalV1alpha2() internalv1alpha2.InternalV1alpha2Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	bindingsV1alpha1 *bindingsv1alpha1.BindingsV1alpha1Client
	duckV1alpha1     *duckv1alpha1.DuckV1alpha1Client
	serviceV1alpha2  *servicev1alpha2.ServiceV1alpha2Client
	internalV1alpha2 *internalv1alpha2.InternalV1alpha2Client
}

// BindingsV1alpha1 retrieves the BindingsV1alpha1Client
func (c *Clientset) BindingsV1alpha1() bindingsv1alpha1.BindingsV1alpha1Interface {
	return c.bindingsV1alpha1
}

// DuckV1alpha1 retrieves the DuckV1alpha1Client
func (c *Clientset) DuckV1alpha1() duckv1alpha1.DuckV1alpha1Interface {
	return c.duckV1alpha1
}

// ServiceV1alpha2 retrieves the ServiceV1alpha2Client
func (c *Clientset) ServiceV1alpha2() servicev1alpha2.ServiceV1alpha2Interface {
	return c.serviceV1alpha2
}

// InternalV1alpha2 retrieves the InternalV1alpha2Client
func (c *Clientset) InternalV1alpha2() internalv1alpha2.InternalV1alpha2Interface {
	return c.internalV1alpha2
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("Burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.bindingsV1alpha1, err = bindingsv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.duckV1alpha1, err = duckv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.serviceV1alpha2, err = servicev1alpha2.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.internalV1alpha2, err = internalv1alpha2.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.bindingsV1alpha1 = bindingsv1alpha1.NewForConfigOrDie(c)
	cs.duckV1alpha1 = duckv1alpha1.NewForConfigOrDie(c)
	cs.serviceV1alpha2 = servicev1alpha2.NewForConfigOrDie(c)
	cs.internalV1alpha2 = internalv1alpha2.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.bindingsV1alpha1 = bindingsv1alpha1.New(c)
	cs.duckV1alpha1 = duckv1alpha1.New(c)
	cs.serviceV1alpha2 = servicev1alpha2.New(c)
	cs.internalV1alpha2 = internalv1alpha2.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
