#! Copyright 2021 VMware Inc. All rights reserved

#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
kind: Secret
metadata:
  name: reg-creds
  namespace: service-bindings
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

#@overlay/match by=overlay.subset({"apiVersion": "apps/v1", "kind": "Deployment"})
---
spec:
  template:
    spec:
      #@overlay/match when=0
      imagePullSecrets:
      - name: reg-creds
